<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divsidebar-overlay</name>
   <tag></tag>
   <elementGuidId>026c28ad-3ddb-41f8-b9ff-fc12ddf2f62e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-overlay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sidebar-overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e3f6b7a-01c5-4828-a15a-0c2fbfc2cf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebar-overlay</value>
      <webElementGuid>27b4b708-e48b-46c2-830c-b4d72b7d5404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-overlay&quot;)</value>
      <webElementGuid>4676bb85-411d-4d9b-921b-5380a1d14061</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sidebar-overlay']</value>
      <webElementGuid>df1e5791-3839-4da8-a112-a12307e38562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>1f070a2b-a05b-41f7-b2ce-066a9b71751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sidebar-overlay']</value>
      <webElementGuid>f891fe14-9c44-4e9d-a34c-1962fb88cdfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
