<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox_manufacturers</name>
   <tag></tag>
   <elementGuidId>0d18861d-5049-4b65-aee9-e2b8062a353a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='checkbox_manufacturers']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;checkbox_manufacturers&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26d94981-17ad-4819-82a2-f47b6aa1d2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkbox_manufacturers</value>
      <webElementGuid>084e8922-9c0e-4009-b3b9-c1dad8495244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1599c648-cc2f-44bd-8634-e56677dcbbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>45c36188-8b4e-47af-88ad-b301d917e345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkboxGroups</value>
      <webElementGuid>d987384d-5612-42e2-8976-e435914ddc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manufacturers-grid&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/input[@class=&quot;checkboxGroups&quot;]</value>
      <webElementGuid>82b7560b-c8d9-4efd-b4c9-12c4063bbb09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='checkbox_manufacturers']</value>
      <webElementGuid>c8c445b8-a800-4c52-8b7d-54e12d7e9b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='manufacturers-grid']/tbody/tr/td/input</value>
      <webElementGuid>a4fe3c2f-6883-42b9-9fd4-4694af776f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>78baf5b4-4065-44fc-9422-652a8d05f4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'checkbox_manufacturers' and @type = 'checkbox']</value>
      <webElementGuid>70740c04-9bfd-4963-b83f-cda1fb5d3bb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
