<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_org.openqa.selenium</name>
   <tag></tag>
   <elementGuidId>36db633c-5c4f-4278-ac2d-eca6fa52e785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-first.even-row-color > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='related-package-summary']/div[2]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94b7f79c-6003-462f-9190-27b57a26069f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../package-summary.html</value>
      <webElementGuid>3bcece4e-3fc8-4ba1-aba1-163086a812f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium</value>
      <webElementGuid>293030ec-6440-4214-8880-3a343e788fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;related-package-summary&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first even-row-color&quot;]/a[1]</value>
      <webElementGuid>e00a5e6c-ac9a-4c76-90fe-852d4ab714ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='related-package-summary']/div[2]/div[3]/a</value>
      <webElementGuid>6c08214b-1d94-4f5f-9049-46ba47bdc63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'org.openqa.selenium')]</value>
      <webElementGuid>77e6291b-01ab-4ba3-8510-8b34dba735ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../package-summary.html')]</value>
      <webElementGuid>900f0d43-fc2a-40d5-bb5d-25b7af3976b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>d3e03420-d2b2-4dbd-9326-cec6bed7c071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../package-summary.html' and (text() = 'org.openqa.selenium' or . = 'org.openqa.selenium')]</value>
      <webElementGuid>61cb08e4-8b82-4790-b09b-7b45ff7aa686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
