<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_org.openqa.selenium</name>
   <tag></tag>
   <elementGuidId>2f18bc07-f773-4755-a360-4bc380c7bf4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-first.even-row-color.all-packages-table.all-packages-table-tab1 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='all-packages-table']/div[2]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e878dd30-f4bd-4cb0-bb08-88913b4e2e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/package-summary.html</value>
      <webElementGuid>6c9708b3-e475-4a94-b942-208f2c5b8b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium</value>
      <webElementGuid>5111ffac-a495-4b34-a5fd-5adfb452bb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all-packages-table&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first even-row-color all-packages-table all-packages-table-tab1&quot;]/a[1]</value>
      <webElementGuid>7451a208-55cc-4767-be93-bf90ad8ff1aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-packages-table']/div[2]/div[3]/a</value>
      <webElementGuid>4d0f1e5c-a61a-44ab-94c6-7a9b734b8453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'org.openqa.selenium')]</value>
      <webElementGuid>3516556b-ed35-4d76-a829-5b40a9ba74b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/package-summary.html')]</value>
      <webElementGuid>fbdf86dc-3c80-44f2-a34d-3cfcc928dced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>a9f7acfa-6037-4899-b2d7-e2580cd43f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/package-summary.html' and (text() = 'org.openqa.selenium' or . = 'org.openqa.selenium')]</value>
      <webElementGuid>e3feefab-9d7e-492a-84b7-c6d27c9070ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
