<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_org.openqa.selenium.bidi</name>
   <tag></tag>
   <elementGuidId>a31d3b54-7561-4978-ae6f-0183f3ce0bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-first.odd-row-color.all-packages-table.all-packages-table-tab1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='all-packages-table']/div[2]/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ca0d30c3-4801-4566-acc1-34f50acdbf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-first odd-row-color all-packages-table all-packages-table-tab1</value>
      <webElementGuid>81ac7212-ceec-40b1-9012-d82d1deb13f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium.bidi</value>
      <webElementGuid>51e71f74-0df4-4ca4-81a4-0906cbc1bfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all-packages-table&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first odd-row-color all-packages-table all-packages-table-tab1&quot;]</value>
      <webElementGuid>04a5cc7f-1a87-40d3-9823-6b1dd3f50d7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-packages-table']/div[2]/div[5]</value>
      <webElementGuid>11983241-c85d-435b-a904-7f4e045324bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>c2091f58-8bb2-4bef-97b5-378b39223bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'org.openqa.selenium.bidi' or . = 'org.openqa.selenium.bidi')]</value>
      <webElementGuid>8fc27e59-adf8-4242-a8f7-25e569963efd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
