<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Class</name>
   <tag></tag>
   <elementGuidId>80c5ea2a-0298-4401-9c04-3ac29ac8da2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navbar-top-firstrow']/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ccde51ec-9df9-4cde-9c49-a0b21b718e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Class</value>
      <webElementGuid>16c7cc2f-cb62-419b-bb7a-93ed5b2a52d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-top-firstrow&quot;)/li[3]</value>
      <webElementGuid>b924a87d-ea6a-4a24-83bf-5ac25146502b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navbar-top-firstrow']/li[3]</value>
      <webElementGuid>0853d8b7-9ff1-4321-9458-74e89ebcf4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>6029f465-232c-43e9-840d-5b12b7b0829f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Class' or . = 'Class')]</value>
      <webElementGuid>fd83c13a-2912-4573-9342-c34dd3bee580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
