<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Exceptions</name>
   <tag></tag>
   <elementGuidId>3a00213e-dc9f-448e-9b6d-d18b868dffa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#class-summary-tab5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='class-summary-tab5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36fc56e2-3720-4470-8b5e-4cea348b57cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>class-summary-tab5</value>
      <webElementGuid>9ff2d9bb-8e69-4804-a4f0-60264e89bf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5609a50c-5e47-40fc-8fbc-0bde74b85f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4faf81fb-a7a0-434f-8af7-52284fa8ecc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>class-summary.tabpanel</value>
      <webElementGuid>8d02e730-c8b8-45a2-a136-a26d64d16759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>afd7b723-46f2-4be6-89c5-64d3a1034f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>switchTab(event)</value>
      <webElementGuid>3b6d44ff-1ba0-4e18-b15e-e7091d80d876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show('class-summary', 'class-summary-tab5', 2)</value>
      <webElementGuid>3bebae34-b4f4-4e31-8caf-39b8e64fae5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-tab</value>
      <webElementGuid>a68fdaf6-35da-479a-a673-feaf011c9323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exceptions</value>
      <webElementGuid>ac4889f0-2355-4d8e-8f96-5588992194d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary-tab5&quot;)</value>
      <webElementGuid>3ddbf6c8-ecdd-4eb0-b244-9e7876f5208f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='class-summary-tab5']</value>
      <webElementGuid>e68c9975-0186-41fb-bbed-4a736ef2a83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary']/div/button[5]</value>
      <webElementGuid>b35c06e3-9887-4cdd-b89d-0b2ed1543446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>101b9fa4-b09f-42bb-9bb5-acd78446a521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'class-summary-tab5' and (text() = 'Exceptions' or . = 'Exceptions')]</value>
      <webElementGuid>400d2de7-58ce-4098-8dac-ea76cb592011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
