<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>274a3da1-08b0-4efb-8870-eeaf2dd821f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-last.class-summary.class-summary-tab1.odd-row-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='class-summary.tabpanel']/div/div[32]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdb49769-fd68-4b19-bdf1-65dd4604b68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-last class-summary class-summary-tab1 odd-row-color</value>
      <webElementGuid>c4966283-1639-4663-9287-44e6e5f112a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>7351361f-576b-444a-860d-158c6abb016f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary.tabpanel&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-last class-summary class-summary-tab1 odd-row-color&quot;]</value>
      <webElementGuid>ac2fe97f-7e11-4ab8-8b5a-32ac7702f57f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary.tabpanel']/div/div[32]</value>
      <webElementGuid>df1f5687-9591-40d9-befd-965c47d18c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[32]</value>
      <webElementGuid>e6fc40f8-29e9-4928-8353-3367f90e8414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>43d1f982-411f-402b-a525-ae6ca2f4594b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
