<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputsearch-input</name>
   <tag></tag>
   <elementGuidId>2eb1ea00-dd84-4253-9ec2-17caa66815db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0b10bbf-3b46-44e6-b55f-12c86547aeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23707138-9bdb-488d-b6ac-26a7a51f7e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>7cbe0876-c64e-490e-8e3c-3096459ebda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>fa4b8ad1-87ff-4b0a-867f-f6c23070ed99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>watermark ui-autocomplete-input</value>
      <webElementGuid>a2d710b3-7b98-4824-b63f-193e778d89a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f8415894-260d-4ace-ad08-01416795c84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-input&quot;)</value>
      <webElementGuid>50d7005e-0a5d-4cf9-9e8d-30b9cda764b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-input']</value>
      <webElementGuid>b5eb2203-018f-4fee-b051-bb344fcb6704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>59228950-30c8-4364-b99c-47ed541b4c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'search-input']</value>
      <webElementGuid>a6527ec7-2565-4d83-b8eb-2dbb1e20e96e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
